### ISSUE TITLE
SorxCODE! CONTACT ME IMMIDIATLY PLEASE!

### ISSUE THREAD

**Issue by rogasciences** [sorXCode/Sentiment-Analyzer#3]
I never received your order from fiverr. I only have the postman app, and you didn't provide me with the github project! 

A.K.A - session, Co2 etc guy.
Please contact me as soon as possible.
burnitupdown@gmail.com

**Comment by sorXCode** [comment]
@rogasciences 
Hi, I initiated the repo transfer earlier, can you check your mail for that?

I've also added you as collaborator for the repo. [! Click here to access the repo](https://github.com/sorXCode/stream_co2)
